import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

// components
import Navbar from "./components/Navbar/Navbar";
import ClientOnly from "./components/ClientOnly";
import RegisterModal from "./components/modals/RegisterModal";

const font = Nunito({subsets: ['latin']})

export const metadata: Metadata = {
  title: "Airbnb Clone",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <RegisterModal/>
          <Navbar/>
        </ClientOnly>
    
        {children}
        </body>
    </html>
  );
}
